<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\State;
use App\Models\City;

class CountrySateCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $country = Country::create(['name' => 'India']);
        
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Andhra Pradesh']);
        City::create(['state_id' => $state->id, 'name' => 'Adoni']);
        City::create(['state_id' => $state->id, 'name' => 'Amaravati']);
        City::create(['state_id' => $state->id, 'name' => 'Anantapur']);
        City::create(['state_id' => $state->id, 'name' => 'Chandragiri']);
        City::create(['state_id' => $state->id, 'name' => 'Chittoor']);
        City::create(['state_id' => $state->id, 'name' => 'Dowlaiswaram']);
        City::create(['state_id' => $state->id, 'name' => 'Eluru']);
        City::create(['state_id' => $state->id, 'name' => 'Guntur']);
        City::create(['state_id' => $state->id, 'name' => 'Kadapa']);
        City::create(['state_id' => $state->id, 'name' => 'Kakinada']);
        City::create(['state_id' => $state->id, 'name' => 'Kurnool']);
        City::create(['state_id' => $state->id, 'name' => 'Machilipatnam']);
        City::create(['state_id' => $state->id, 'name' => 'Nagarjunakoṇḍa']);
        City::create(['state_id' => $state->id, 'name' => 'Rajahmundry']);
        City::create(['state_id' => $state->id, 'name' => 'Srikakulam']);
        City::create(['state_id' => $state->id, 'name' => 'Tirupati']);
        City::create(['state_id' => $state->id, 'name' => 'Vijayawada']);
        City::create(['state_id' => $state->id, 'name' => 'Visakhapatnam']);
        City::create(['state_id' => $state->id, 'name' => 'Vizianagaram']);
        City::create(['state_id' => $state->id, 'name' => 'Yemmiganur']);
        

        $state = State::create(['country_id' => $country->id, 'name' => 'Arunachal Pradesh']);
        City::create(['state_id' => $state->id, 'name' => 'Itanagar']);
        

        $state = State::create(['country_id' => $country->id, 'name' => 'Assam']);
        City::create(['state_id' => $state->id, 'name' => 'Dhuburi']);
        City::create(['state_id' => $state->id, 'name' => 'Dibrugarh']);
        City::create(['state_id' => $state->id, 'name' => 'Dispur']);
        City::create(['state_id' => $state->id, 'name' => 'Guwahati']);
        City::create(['state_id' => $state->id, 'name' => 'Jorhat']);
        City::create(['state_id' => $state->id, 'name' => 'Nagaon']);
        City::create(['state_id' => $state->id, 'name' => 'Sivasagar']);
        City::create(['state_id' => $state->id, 'name' => 'Silchar']);
        City::create(['state_id' => $state->id, 'name' => 'Tezpur']);
        City::create(['state_id' => $state->id, 'name' => 'Tinsukia']);
       
        $state = State::create(['country_id' => $country->id, 'name' => 'Bihar']);
        City::create(['state_id' => $state->id, 'name' => 'Ara']);
        City::create(['state_id' => $state->id, 'name' => 'Barauni']);
        City::create(['state_id' => $state->id, 'name' => 'Begusarai']);
        City::create(['state_id' => $state->id, 'name' => 'Bettiah']);
        City::create(['state_id' => $state->id, 'name' => 'Bhagalpur']);
        City::create(['state_id' => $state->id, 'name' => 'Bihar Sharif']);
        City::create(['state_id' => $state->id, 'name' => 'Bodh Gaya']);
        City::create(['state_id' => $state->id, 'name' => 'Buxar']);
        City::create(['state_id' => $state->id, 'name' => 'Chapra']);
        City::create(['state_id' => $state->id, 'name' => 'Darbhanga']);
        City::create(['state_id' => $state->id, 'name' => 'Dehri']);
        City::create(['state_id' => $state->id, 'name' => 'Dinapur Nizamat']);
        City::create(['state_id' => $state->id, 'name' => 'Gaya']);
        City::create(['state_id' => $state->id, 'name' => 'Hajipur']);
        City::create(['state_id' => $state->id, 'name' => 'Jamalpur']);
        City::create(['state_id' => $state->id, 'name' => 'Katihar']);
        City::create(['state_id' => $state->id, 'name' => 'Madhubani']);
        City::create(['state_id' => $state->id, 'name' => 'Motihari']);
        City::create(['state_id' => $state->id, 'name' => 'Munger']);
        City::create(['state_id' => $state->id, 'name' => 'Muzaffarpur']);
        City::create(['state_id' => $state->id, 'name' => 'Patna']);
        City::create(['state_id' => $state->id, 'name' => 'Purnia']);
        City::create(['state_id' => $state->id, 'name' => 'Pusa']);
        City::create(['state_id' => $state->id, 'name' => 'Saharsa']);
        City::create(['state_id' => $state->id, 'name' => 'Samastipur']);
        City::create(['state_id' => $state->id, 'name' => 'Sasaram']);
        City::create(['state_id' => $state->id, 'name' => 'Sitamarhi']);
        City::create(['state_id' => $state->id, 'name' => 'Siwan']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Chhattisgarh']);
        City::create(['state_id' => $state->id, 'name' => 'Ambikapur']);
        City::create(['state_id' => $state->id, 'name' => 'Bhilai']);
        City::create(['state_id' => $state->id, 'name' => 'Bilaspur']);
        City::create(['state_id' => $state->id, 'name' => 'Dhamtari']);
        City::create(['state_id' => $state->id, 'name' => 'Durg']);
        City::create(['state_id' => $state->id, 'name' => 'Jagdalpur']);
        City::create(['state_id' => $state->id, 'name' => 'Raipur']);
        City::create(['state_id' => $state->id, 'name' => 'Rajnandgaon']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Delhi']);
        City::create(['state_id' => $state->id, 'name' => 'Delhi']);
        City::create(['state_id' => $state->id, 'name' => 'New Delhi']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Goa']);
        City::create(['state_id' => $state->id, 'name' => 'Madgaon']);
        City::create(['state_id' => $state->id, 'name' => 'Panaji']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Gujarat']);
        City::create(['state_id' => $state->id, 'name' => 'Ahmadabad']);
        City::create(['state_id' => $state->id, 'name' => 'Amreli']);
        City::create(['state_id' => $state->id, 'name' => 'Bharuch']);
        City::create(['state_id' => $state->id, 'name' => 'Bhavnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Bhuj']);
        City::create(['state_id' => $state->id, 'name' => 'Dwarka']);
        City::create(['state_id' => $state->id, 'name' => 'Gandhinagar']);
        City::create(['state_id' => $state->id, 'name' => 'Godhra']);
        City::create(['state_id' => $state->id, 'name' => 'Jamnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Junagadh']);
        City::create(['state_id' => $state->id, 'name' => 'Kandla']);
        City::create(['state_id' => $state->id, 'name' => 'Khambhat']);
        City::create(['state_id' => $state->id, 'name' => 'Kheda']);
        City::create(['state_id' => $state->id, 'name' => 'Mahesana']);
        City::create(['state_id' => $state->id, 'name' => 'Morbi']);
        City::create(['state_id' => $state->id, 'name' => 'Nadiad']);
        City::create(['state_id' => $state->id, 'name' => 'Navsari']);
        City::create(['state_id' => $state->id, 'name' => 'Okha']);
        City::create(['state_id' => $state->id, 'name' => 'Palanpur']);
        City::create(['state_id' => $state->id, 'name' => 'Patan']);
        City::create(['state_id' => $state->id, 'name' => 'Porbandar']);
        City::create(['state_id' => $state->id, 'name' => 'Rajkot']);
        City::create(['state_id' => $state->id, 'name' => 'Surat']);
        City::create(['state_id' => $state->id, 'name' => 'Surendranagar']);
        City::create(['state_id' => $state->id, 'name' => 'Valsad']);
        City::create(['state_id' => $state->id, 'name' => 'Veraval']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Haryana']);
        City::create(['state_id' => $state->id, 'name' => 'Ambala']);
        City::create(['state_id' => $state->id, 'name' => 'Bhiwani']);
        City::create(['state_id' => $state->id, 'name' => 'Chandigarh']);
        City::create(['state_id' => $state->id, 'name' => 'Faridabad']);
        City::create(['state_id' => $state->id, 'name' => 'Firozpur Jhirka']);
        City::create(['state_id' => $state->id, 'name' => 'Gurugram']);
        City::create(['state_id' => $state->id, 'name' => 'Hansi']);
        City::create(['state_id' => $state->id, 'name' => 'Hisar']);
        City::create(['state_id' => $state->id, 'name' => 'Jind']);
        City::create(['state_id' => $state->id, 'name' => 'Kaithal']);
        City::create(['state_id' => $state->id, 'name' => 'Karnal']);
        City::create(['state_id' => $state->id, 'name' => 'Kurukshetra']);
        City::create(['state_id' => $state->id, 'name' => 'Panipat']);
        City::create(['state_id' => $state->id, 'name' => 'Pehowa']);
        City::create(['state_id' => $state->id, 'name' => 'Rewari']);
        City::create(['state_id' => $state->id, 'name' => 'Rohtak']);
        City::create(['state_id' => $state->id, 'name' => 'Sirsa']);
        City::create(['state_id' => $state->id, 'name' => 'Sonipat']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Himachal Pradesh']);
        City::create(['state_id' => $state->id, 'name' => 'Bilaspur']);
        City::create(['state_id' => $state->id, 'name' => 'Chamba']);
        City::create(['state_id' => $state->id, 'name' => 'Dalhousie']);
        City::create(['state_id' => $state->id, 'name' => 'Dharmshala']);
        City::create(['state_id' => $state->id, 'name' => 'Hamirpur']);
        City::create(['state_id' => $state->id, 'name' => 'Kangra']);
        City::create(['state_id' => $state->id, 'name' => 'Kullu']);
        City::create(['state_id' => $state->id, 'name' => 'Mandi']);
        City::create(['state_id' => $state->id, 'name' => 'Nahan']);
        City::create(['state_id' => $state->id, 'name' => 'Shimla']);
        City::create(['state_id' => $state->id, 'name' => 'Una']);
        

        $state = State::create(['country_id' => $country->id, 'name' => 'Jharkhand']);
        City::create(['state_id' => $state->id, 'name' => 'Bokaro']);
        City::create(['state_id' => $state->id, 'name' => 'Chaibasa']);
        City::create(['state_id' => $state->id, 'name' => 'Deoghar']);
        City::create(['state_id' => $state->id, 'name' => 'Dhanbad']);
        City::create(['state_id' => $state->id, 'name' => 'Dumka']);
        City::create(['state_id' => $state->id, 'name' => 'Giridih']);
        City::create(['state_id' => $state->id, 'name' => 'Hazaribag']);
        City::create(['state_id' => $state->id, 'name' => 'Jamshedpur']);
        City::create(['state_id' => $state->id, 'name' => 'Jharia']);
        City::create(['state_id' => $state->id, 'name' => 'Rajmahal']);
        City::create(['state_id' => $state->id, 'name' => 'Ranchi']);
        City::create(['state_id' => $state->id, 'name' => 'Saraikela']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Karnataka']);
        City::create(['state_id' => $state->id, 'name' => 'Badami']);
        City::create(['state_id' => $state->id, 'name' => 'Ballari']);
        City::create(['state_id' => $state->id, 'name' => 'Bengaluru']);
        City::create(['state_id' => $state->id, 'name' => 'Belagavi']);
        City::create(['state_id' => $state->id, 'name' => 'Bhadravati']);
        City::create(['state_id' => $state->id, 'name' => 'Bidar']);
        City::create(['state_id' => $state->id, 'name' => 'Chikkamagaluru']);
        City::create(['state_id' => $state->id, 'name' => 'Chitradurga']);
        City::create(['state_id' => $state->id, 'name' => 'Davangere']);
        City::create(['state_id' => $state->id, 'name' => 'Halebid']);
        City::create(['state_id' => $state->id, 'name' => 'Hassan']);
        City::create(['state_id' => $state->id, 'name' => 'Hubballi-Dharwad']);
        City::create(['state_id' => $state->id, 'name' => 'Kalaburagi']);
        City::create(['state_id' => $state->id, 'name' => 'Kolar']);
        City::create(['state_id' => $state->id, 'name' => 'Madikeri']);
        City::create(['state_id' => $state->id, 'name' => 'Mandya']);
        City::create(['state_id' => $state->id, 'name' => 'Mangaluru']);
        City::create(['state_id' => $state->id, 'name' => 'Mysuru']);
        City::create(['state_id' => $state->id, 'name' => 'Raichur']);
        City::create(['state_id' => $state->id, 'name' => 'Shivamogga']);
        City::create(['state_id' => $state->id, 'name' => 'Shravanabelagola']);
        City::create(['state_id' => $state->id, 'name' => 'Shrirangapattana']);
        City::create(['state_id' => $state->id, 'name' => 'Tumakuru']);
        City::create(['state_id' => $state->id, 'name' => 'Vijayapura']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Kerala']);
        City::create(['state_id' => $state->id, 'name' => 'Alappuzha']);
        City::create(['state_id' => $state->id, 'name' => 'Vatakara']);
        City::create(['state_id' => $state->id, 'name' => 'Idukki']);
        City::create(['state_id' => $state->id, 'name' => 'Kannur']);
        City::create(['state_id' => $state->id, 'name' => 'Kochi']);
        City::create(['state_id' => $state->id, 'name' => 'Kollam']);
        City::create(['state_id' => $state->id, 'name' => 'Kottayam']);
        City::create(['state_id' => $state->id, 'name' => 'Kozhikode']);
        City::create(['state_id' => $state->id, 'name' => 'Mattancheri']);
        City::create(['state_id' => $state->id, 'name' => 'Palakkad']);
        City::create(['state_id' => $state->id, 'name' => 'Thalassery']);
        City::create(['state_id' => $state->id, 'name' => 'Thiruvananthapuram']);
        City::create(['state_id' => $state->id, 'name' => 'Thrissur']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Madhya Pradesh']);
        City::create(['state_id' => $state->id, 'name' => 'Balaghat']);
        City::create(['state_id' => $state->id, 'name' => 'Barwani']);
        City::create(['state_id' => $state->id, 'name' => 'Betul']);
        City::create(['state_id' => $state->id, 'name' => 'Bharhut']);
        City::create(['state_id' => $state->id, 'name' => 'Bhind']);
        City::create(['state_id' => $state->id, 'name' => 'Bhojpur']);
        City::create(['state_id' => $state->id, 'name' => 'Bhopal']);
        City::create(['state_id' => $state->id, 'name' => 'Burhanpur']);
        City::create(['state_id' => $state->id, 'name' => 'Kottayam']);
        City::create(['state_id' => $state->id, 'name' => 'Chhatarpur']);
        City::create(['state_id' => $state->id, 'name' => 'Chhindwara']);
        City::create(['state_id' => $state->id, 'name' => 'Damoh']);
        City::create(['state_id' => $state->id, 'name' => 'Datia']);
        City::create(['state_id' => $state->id, 'name' => 'Dewas']);
        City::create(['state_id' => $state->id, 'name' => 'Dhar']);
        City::create(['state_id' => $state->id, 'name' => 'Dr. Ambedkar Nagar (Mhow)']);
        City::create(['state_id' => $state->id, 'name' => 'Guna']);
        City::create(['state_id' => $state->id, 'name' => 'Gwalior']);
        City::create(['state_id' => $state->id, 'name' => 'Hoshangabad']);
        City::create(['state_id' => $state->id, 'name' => 'Indore']);
        City::create(['state_id' => $state->id, 'name' => 'Itarsi']);
        City::create(['state_id' => $state->id, 'name' => 'Jabalpur']);
        City::create(['state_id' => $state->id, 'name' => 'Jhabua']);
        City::create(['state_id' => $state->id, 'name' => 'Khajuraho']);
        City::create(['state_id' => $state->id, 'name' => 'Khandwa']);
        City::create(['state_id' => $state->id, 'name' => 'Khargone']);
        City::create(['state_id' => $state->id, 'name' => 'Maheshwar']);
        City::create(['state_id' => $state->id, 'name' => 'Mandla']);
        City::create(['state_id' => $state->id, 'name' => 'Mandsaur']);
        City::create(['state_id' => $state->id, 'name' => 'Morena']);
        City::create(['state_id' => $state->id, 'name' => 'Murwara']);
        City::create(['state_id' => $state->id, 'name' => 'Narsimhapur']);
        City::create(['state_id' => $state->id, 'name' => 'Narsinghgarh']);
        City::create(['state_id' => $state->id, 'name' => 'Narwar']);
        City::create(['state_id' => $state->id, 'name' => 'Neemuch']);
        City::create(['state_id' => $state->id, 'name' => 'Nowgong']);
        City::create(['state_id' => $state->id, 'name' => 'Orchha']);
        City::create(['state_id' => $state->id, 'name' => 'Panna']);
        City::create(['state_id' => $state->id, 'name' => 'Raisen']);
        City::create(['state_id' => $state->id, 'name' => 'Rajgarh']);
        City::create(['state_id' => $state->id, 'name' => 'Ratlam']);
        City::create(['state_id' => $state->id, 'name' => 'Rewa']);
        City::create(['state_id' => $state->id, 'name' => 'Sagar']);
        City::create(['state_id' => $state->id, 'name' => 'Sarangpur']);
        City::create(['state_id' => $state->id, 'name' => 'Satna']);
        City::create(['state_id' => $state->id, 'name' => 'Sehore']);
        City::create(['state_id' => $state->id, 'name' => 'Seoni']);
        City::create(['state_id' => $state->id, 'name' => 'Shahdol']);
        City::create(['state_id' => $state->id, 'name' => 'Shajapur']);
        City::create(['state_id' => $state->id, 'name' => 'Sheopur']);
        City::create(['state_id' => $state->id, 'name' => 'Shivpuri']);
        City::create(['state_id' => $state->id, 'name' => 'Ujjain']);
        City::create(['state_id' => $state->id, 'name' => 'Vidisha']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Maharashtra']);
        City::create(['state_id' => $state->id, 'name' => 'Ahmadnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Akola']);
        City::create(['state_id' => $state->id, 'name' => 'Amravati']);
        City::create(['state_id' => $state->id, 'name' => 'Aurangabad']);
        City::create(['state_id' => $state->id, 'name' => 'Bhandara']);
        City::create(['state_id' => $state->id, 'name' => 'Bhusawal']);
        City::create(['state_id' => $state->id, 'name' => 'Bid']);
        City::create(['state_id' => $state->id, 'name' => 'Buldhana']);
        City::create(['state_id' => $state->id, 'name' => 'Chandrapur']);
        City::create(['state_id' => $state->id, 'name' => 'Daulatabad']);
        City::create(['state_id' => $state->id, 'name' => 'Dhule']);
        City::create(['state_id' => $state->id, 'name' => 'Jalgaon']);
        City::create(['state_id' => $state->id, 'name' => 'Kalyan']);
        City::create(['state_id' => $state->id, 'name' => 'Karli']);
        City::create(['state_id' => $state->id, 'name' => 'Kolhapur']);
        City::create(['state_id' => $state->id, 'name' => 'Mahabaleshwar']);
        City::create(['state_id' => $state->id, 'name' => 'Malegaon']);
        City::create(['state_id' => $state->id, 'name' => 'Matheran']);
        City::create(['state_id' => $state->id, 'name' => 'Mumbai']);
        City::create(['state_id' => $state->id, 'name' => 'Nagpur']);
        City::create(['state_id' => $state->id, 'name' => 'Nanded']);
        City::create(['state_id' => $state->id, 'name' => 'Nashik']);
        City::create(['state_id' => $state->id, 'name' => 'Osmanabad']);
        City::create(['state_id' => $state->id, 'name' => 'Pandharpur']);
        City::create(['state_id' => $state->id, 'name' => 'Parbhani']);
        City::create(['state_id' => $state->id, 'name' => 'Pune']);
        City::create(['state_id' => $state->id, 'name' => 'Ratnagiri']);
        City::create(['state_id' => $state->id, 'name' => 'Sangli']);
        City::create(['state_id' => $state->id, 'name' => 'Satara']);
        City::create(['state_id' => $state->id, 'name' => 'Sevagram']);
        City::create(['state_id' => $state->id, 'name' => 'Solapur']);
        City::create(['state_id' => $state->id, 'name' => 'Thane']);
        City::create(['state_id' => $state->id, 'name' => 'Ulhasnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Vasai-Virar']);
        City::create(['state_id' => $state->id, 'name' => 'Wardha']);
        City::create(['state_id' => $state->id, 'name' => 'Yavatmal']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Manipur']);
        City::create(['state_id' => $state->id, 'name' => 'Imphal']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Meghalaya']);
        City::create(['state_id' => $state->id, 'name' => 'Cherrapunji']);
        City::create(['state_id' => $state->id, 'name' => 'Shillong']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Mizoram']);
        City::create(['state_id' => $state->id, 'name' => 'Aizawl']);
        City::create(['state_id' => $state->id, 'name' => 'Lunglei']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Nagaland']);
        City::create(['state_id' => $state->id, 'name' => 'Kohima']);
        City::create(['state_id' => $state->id, 'name' => 'Mon']);
        City::create(['state_id' => $state->id, 'name' => 'Phek']);
        City::create(['state_id' => $state->id, 'name' => 'Wokha']);
        City::create(['state_id' => $state->id, 'name' => 'Zunheboto']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Odisha']);
        City::create(['state_id' => $state->id, 'name' => 'Balangir']);
        City::create(['state_id' => $state->id, 'name' => 'Baleshwar']);
        City::create(['state_id' => $state->id, 'name' => 'Baripada']);
        City::create(['state_id' => $state->id, 'name' => 'Bhubaneshwar']);
        City::create(['state_id' => $state->id, 'name' => 'Brahmapur']);
        City::create(['state_id' => $state->id, 'name' => 'Cuttack']);
        City::create(['state_id' => $state->id, 'name' => 'Dhenkanal']);
        City::create(['state_id' => $state->id, 'name' => 'Kendujhar']);
        City::create(['state_id' => $state->id, 'name' => 'Konark']);
        City::create(['state_id' => $state->id, 'name' => 'Koraput']);
        City::create(['state_id' => $state->id, 'name' => 'Paradip']);
        City::create(['state_id' => $state->id, 'name' => 'Phulabani']);
        City::create(['state_id' => $state->id, 'name' => 'Puri']);
        City::create(['state_id' => $state->id, 'name' => 'Sambalpur']);
        City::create(['state_id' => $state->id, 'name' => 'Udayagiri']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Punjab']);
        City::create(['state_id' => $state->id, 'name' => 'Amritsar']);
        City::create(['state_id' => $state->id, 'name' => 'Batala']);
        City::create(['state_id' => $state->id, 'name' => 'Chandigarh']);
        City::create(['state_id' => $state->id, 'name' => 'Faridkot']);
        City::create(['state_id' => $state->id, 'name' => 'Firozpur']);
        City::create(['state_id' => $state->id, 'name' => 'Gurdaspur']);
        City::create(['state_id' => $state->id, 'name' => 'Hoshiarpur']);
        City::create(['state_id' => $state->id, 'name' => 'Jalandhar']);
        City::create(['state_id' => $state->id, 'name' => 'Kapurthala']);
        City::create(['state_id' => $state->id, 'name' => 'Ludhiana']);
        City::create(['state_id' => $state->id, 'name' => 'Nabha']);
        City::create(['state_id' => $state->id, 'name' => 'Patiala']);
        City::create(['state_id' => $state->id, 'name' => 'Rupnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Sangrur']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Rajasthan']);
        City::create(['state_id' => $state->id, 'name' => 'Abu']);
        City::create(['state_id' => $state->id, 'name' => 'Ajmer']);
        City::create(['state_id' => $state->id, 'name' => 'Alwar']);
        City::create(['state_id' => $state->id, 'name' => 'Amer']);
        City::create(['state_id' => $state->id, 'name' => 'Barmer']);
        City::create(['state_id' => $state->id, 'name' => 'Beawar']);
        City::create(['state_id' => $state->id, 'name' => 'Bharatpur']);
        City::create(['state_id' => $state->id, 'name' => 'Bhilwara']);
        City::create(['state_id' => $state->id, 'name' => 'Bikaner']);
        City::create(['state_id' => $state->id, 'name' => 'Bundi']);
        City::create(['state_id' => $state->id, 'name' => 'Chittaurgarh']);
        City::create(['state_id' => $state->id, 'name' => 'Churu']);
        City::create(['state_id' => $state->id, 'name' => 'Dhaulpur']);
        City::create(['state_id' => $state->id, 'name' => 'Dungarpur']);
        City::create(['state_id' => $state->id, 'name' => 'Ganganagar']);
        City::create(['state_id' => $state->id, 'name' => 'Hanumangarh']);
        City::create(['state_id' => $state->id, 'name' => 'Jaipur']);
        City::create(['state_id' => $state->id, 'name' => 'Jaisalmer']);
        City::create(['state_id' => $state->id, 'name' => 'Jalor']);
        City::create(['state_id' => $state->id, 'name' => 'Jhalawar']);
        City::create(['state_id' => $state->id, 'name' => 'Jhunjhunu']);
        City::create(['state_id' => $state->id, 'name' => 'Jodhpur']);
        City::create(['state_id' => $state->id, 'name' => 'Kishangarh']);
        City::create(['state_id' => $state->id, 'name' => 'Kota']);
        City::create(['state_id' => $state->id, 'name' => 'Merta']);
        City::create(['state_id' => $state->id, 'name' => 'Nagaur']);
        City::create(['state_id' => $state->id, 'name' => 'Nathdwara']);
        City::create(['state_id' => $state->id, 'name' => 'Pali']);
        City::create(['state_id' => $state->id, 'name' => 'Phalodi']);
        City::create(['state_id' => $state->id, 'name' => 'Pushkar']);
        City::create(['state_id' => $state->id, 'name' => 'Sawai Madhopur']);
        City::create(['state_id' => $state->id, 'name' => 'Shahpura']);
        City::create(['state_id' => $state->id, 'name' => 'Sikar']);
        City::create(['state_id' => $state->id, 'name' => 'Sirohi']);
        City::create(['state_id' => $state->id, 'name' => 'Tonk']);
        City::create(['state_id' => $state->id, 'name' => 'Udaipur']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Sikkim']);
        City::create(['state_id' => $state->id, 'name' => 'Gangtok']);
        City::create(['state_id' => $state->id, 'name' => 'Gyalshing']);
        City::create(['state_id' => $state->id, 'name' => 'Lachung']);
        City::create(['state_id' => $state->id, 'name' => 'Mangan']);

        $state = State::create(['country_id' => $country->id, 'name' => 'Tamil Nadu']);
        City::create(['state_id' => $state->id, 'name' => 'Arcot']);
        City::create(['state_id' => $state->id, 'name' => 'Chengalpattu']);
        City::create(['state_id' => $state->id, 'name' => 'Chennai']);
        City::create(['state_id' => $state->id, 'name' => 'Chidambaram']);
        City::create(['state_id' => $state->id, 'name' => 'Coimbatore']);
        City::create(['state_id' => $state->id, 'name' => 'Cuddalore']);
        City::create(['state_id' => $state->id, 'name' => 'Dharmapuri']);
        City::create(['state_id' => $state->id, 'name' => 'Dindigul']);
        City::create(['state_id' => $state->id, 'name' => 'Erode']);
        City::create(['state_id' => $state->id, 'name' => 'Kanchipuram']);
        City::create(['state_id' => $state->id, 'name' => 'Kanniyakumari']);
        City::create(['state_id' => $state->id, 'name' => 'Kodaikanal']);
        City::create(['state_id' => $state->id, 'name' => 'Kumbakonam']);
        City::create(['state_id' => $state->id, 'name' => 'Madurai']);
        City::create(['state_id' => $state->id, 'name' => 'Mamallapuram']);
        City::create(['state_id' => $state->id, 'name' => 'Nagappattinam']);
        City::create(['state_id' => $state->id, 'name' => 'Nagercoil']);
        City::create(['state_id' => $state->id, 'name' => 'Palayamkottai']);
        City::create(['state_id' => $state->id, 'name' => 'Pudukkottai']);
        City::create(['state_id' => $state->id, 'name' => 'Rajapalayam']);
        City::create(['state_id' => $state->id, 'name' => 'Ramanathapuram']);
        City::create(['state_id' => $state->id, 'name' => 'Salem']);
        City::create(['state_id' => $state->id, 'name' => 'Thanjavur']);
        City::create(['state_id' => $state->id, 'name' => 'Tiruchchirappalli']);
        City::create(['state_id' => $state->id, 'name' => 'Tirunelveli']);
        City::create(['state_id' => $state->id, 'name' => 'Tiruppur']);
        City::create(['state_id' => $state->id, 'name' => 'Thoothukudi']);
        City::create(['state_id' => $state->id, 'name' => 'Udhagamandalam']);
        City::create(['state_id' => $state->id, 'name' => 'Vellore']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Telangana']);
        City::create(['state_id' => $state->id, 'name' => 'Hyderabad']);
        City::create(['state_id' => $state->id, 'name' => 'Karimnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Khammam']);
        City::create(['state_id' => $state->id, 'name' => 'Mahbubnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Nizamabad']);
        City::create(['state_id' => $state->id, 'name' => 'Sangareddi']);
        City::create(['state_id' => $state->id, 'name' => 'Warangal']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Tripura']);
        City::create(['state_id' => $state->id, 'name' => 'Agartala']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Uttar Pradesh']);
        City::create(['state_id' => $state->id, 'name' => 'Agra']);
        City::create(['state_id' => $state->id, 'name' => 'Aligarh']);
        City::create(['state_id' => $state->id, 'name' => 'Amroha']);
        City::create(['state_id' => $state->id, 'name' => 'Ayodhya']);
        City::create(['state_id' => $state->id, 'name' => 'Azamgarh']);
        City::create(['state_id' => $state->id, 'name' => 'Bahraich']);
        City::create(['state_id' => $state->id, 'name' => 'Ballia']);
        City::create(['state_id' => $state->id, 'name' => 'Banda']);
        City::create(['state_id' => $state->id, 'name' => 'Bara Banki']);
        City::create(['state_id' => $state->id, 'name' => 'Bareilly']);
        City::create(['state_id' => $state->id, 'name' => 'Basti']);
        City::create(['state_id' => $state->id, 'name' => 'Bijnor']);
        City::create(['state_id' => $state->id, 'name' => 'Bithur']);
        City::create(['state_id' => $state->id, 'name' => 'Budaun']);
        City::create(['state_id' => $state->id, 'name' => 'Bulandshahr']);
        City::create(['state_id' => $state->id, 'name' => 'Deoria']);
        City::create(['state_id' => $state->id, 'name' => 'Etah']);
        City::create(['state_id' => $state->id, 'name' => 'Etawah']);
        City::create(['state_id' => $state->id, 'name' => 'Faizabad']);
        City::create(['state_id' => $state->id, 'name' => 'Farrukhabad-cum-Fatehgarh']);
        City::create(['state_id' => $state->id, 'name' => 'Fatehpur']);
        City::create(['state_id' => $state->id, 'name' => 'Fatehpur Sikri']);
        City::create(['state_id' => $state->id, 'name' => 'Ghaziabad']);
        City::create(['state_id' => $state->id, 'name' => 'Ghazipur']);
        City::create(['state_id' => $state->id, 'name' => 'Gonda']);
        City::create(['state_id' => $state->id, 'name' => 'Gorakhpur']);
        City::create(['state_id' => $state->id, 'name' => 'Hamirpur']);
        City::create(['state_id' => $state->id, 'name' => 'Hardoi']);
        City::create(['state_id' => $state->id, 'name' => 'Hathras']);
        City::create(['state_id' => $state->id, 'name' => 'Jalaun']);
        City::create(['state_id' => $state->id, 'name' => 'Jaunpur']);
        City::create(['state_id' => $state->id, 'name' => 'Jhansi']);
        City::create(['state_id' => $state->id, 'name' => 'Kannauj']);
        City::create(['state_id' => $state->id, 'name' => 'Kanpur']);
        City::create(['state_id' => $state->id, 'name' => 'Lakhimpur']);
        City::create(['state_id' => $state->id, 'name' => 'Lalitpur']);
        City::create(['state_id' => $state->id, 'name' => 'Lucknow']);
        City::create(['state_id' => $state->id, 'name' => 'Mainpuri']);
        City::create(['state_id' => $state->id, 'name' => 'Mathura']);
        City::create(['state_id' => $state->id, 'name' => 'Meerut']);
        City::create(['state_id' => $state->id, 'name' => 'Mirzapur-Vindhyachal']);
        City::create(['state_id' => $state->id, 'name' => 'Moradabad']);
        City::create(['state_id' => $state->id, 'name' => 'Muzaffarnagar']);
        City::create(['state_id' => $state->id, 'name' => 'Partapgarh']);
        City::create(['state_id' => $state->id, 'name' => 'Pilibhit']);
        City::create(['state_id' => $state->id, 'name' => 'Prayagraj']);
        City::create(['state_id' => $state->id, 'name' => 'Rae Bareli']);
        City::create(['state_id' => $state->id, 'name' => 'Rampur']);
        City::create(['state_id' => $state->id, 'name' => 'Saharanpur']);
        City::create(['state_id' => $state->id, 'name' => 'Sambhal']);
        City::create(['state_id' => $state->id, 'name' => 'Shahjahanpur']);
        City::create(['state_id' => $state->id, 'name' => 'Sitapur']);
        City::create(['state_id' => $state->id, 'name' => 'Sultanpur']);
        City::create(['state_id' => $state->id, 'name' => 'Tehri']);
        City::create(['state_id' => $state->id, 'name' => 'Varanasi']);
        
        $state = State::create(['country_id' => $country->id, 'name' => 'Uttarakhand']);
        City::create(['state_id' => $state->id, 'name' => 'Almora']);
        City::create(['state_id' => $state->id, 'name' => 'Dehra Dun']);
        City::create(['state_id' => $state->id, 'name' => 'Haridwar']);
        City::create(['state_id' => $state->id, 'name' => 'Mussoorie']);
        City::create(['state_id' => $state->id, 'name' => 'Nainital']);
        City::create(['state_id' => $state->id, 'name' => 'Pithoragarh']);

        $state = State::create(['country_id' => $country->id, 'name' => 'West Bengal']);
        City::create(['state_id' => $state->id, 'name' => 'Alipore']);
        City::create(['state_id' => $state->id, 'name' => 'Alipur Duar']);
        City::create(['state_id' => $state->id, 'name' => 'Asansol']);
        City::create(['state_id' => $state->id, 'name' => 'Baharampur']);
        City::create(['state_id' => $state->id, 'name' => 'Bally']);
        City::create(['state_id' => $state->id, 'name' => 'Balurghat']);
        City::create(['state_id' => $state->id, 'name' => 'Bankura']);
        City::create(['state_id' => $state->id, 'name' => 'Baranagar']);
        City::create(['state_id' => $state->id, 'name' => 'Barasat']);
        City::create(['state_id' => $state->id, 'name' => 'Barrackpore']);
        City::create(['state_id' => $state->id, 'name' => 'Basirhat']);
        City::create(['state_id' => $state->id, 'name' => 'Bhatpara']);
        City::create(['state_id' => $state->id, 'name' => 'Bishnupur']);
        City::create(['state_id' => $state->id, 'name' => 'Budge Budge']);
        City::create(['state_id' => $state->id, 'name' => 'Burdwan']);
        City::create(['state_id' => $state->id, 'name' => 'Chandernagore']);
        City::create(['state_id' => $state->id, 'name' => 'Darjeeling']);
        City::create(['state_id' => $state->id, 'name' => 'Diamond Harbour']);
        City::create(['state_id' => $state->id, 'name' => 'Dum Dum']);
        City::create(['state_id' => $state->id, 'name' => 'Durgapur']);
        City::create(['state_id' => $state->id, 'name' => 'Halisahar']);
        City::create(['state_id' => $state->id, 'name' => 'Haora']);
        City::create(['state_id' => $state->id, 'name' => 'Hugli']);
        City::create(['state_id' => $state->id, 'name' => 'Ingraj Bazar']);
        City::create(['state_id' => $state->id, 'name' => 'Jalpaiguri']);
        City::create(['state_id' => $state->id, 'name' => 'Kalimpong']);
        City::create(['state_id' => $state->id, 'name' => 'Kamarhati']);
        City::create(['state_id' => $state->id, 'name' => 'Kanchrapara']);
        City::create(['state_id' => $state->id, 'name' => 'Kharagpur']);
        City::create(['state_id' => $state->id, 'name' => 'Cooch Behar']);
        City::create(['state_id' => $state->id, 'name' => 'Kolkata']);
        City::create(['state_id' => $state->id, 'name' => 'Krishnanagar']);
        City::create(['state_id' => $state->id, 'name' => 'Malda']);
        City::create(['state_id' => $state->id, 'name' => 'Midnapore']);
        City::create(['state_id' => $state->id, 'name' => 'Murshidabad']);
        City::create(['state_id' => $state->id, 'name' => 'Nabadwip']);
        City::create(['state_id' => $state->id, 'name' => 'Palashi']);
        City::create(['state_id' => $state->id, 'name' => 'Panihati']);
        City::create(['state_id' => $state->id, 'name' => 'Purulia']);
        City::create(['state_id' => $state->id, 'name' => 'Raiganj']);
        City::create(['state_id' => $state->id, 'name' => 'Santipur']);
        City::create(['state_id' => $state->id, 'name' => 'Shantiniketan']);
        City::create(['state_id' => $state->id, 'name' => 'Shrirampur']);
        City::create(['state_id' => $state->id, 'name' => 'Siliguri']);
        City::create(['state_id' => $state->id, 'name' => 'Siuri']);
        City::create(['state_id' => $state->id, 'name' => 'Tamluk']);
        City::create(['state_id' => $state->id, 'name' => 'Titagarh']);
    }
}
